### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#151]
As the modpack is not limited to CF anymore, it could use a simple static website.

- [ ] [Pick a theme](https://startbootstrap.com/?showPro=false)
- [ ] Copy to a separate branch
- [ ] Decide on the most important content
  - Download buttons
    - CF (CF, MultiMC, GDLauncher)
    - Others
  - Video
  - Main features
    - Performance
    - OF compatibility/shaders
    - "Vanilla tweaks"
    - Latest Minecraft
    - "Works everywhere" - in every server and in different launchers
    - Open development
  - Support links
    - CF  
    - GitHub
    - Discord
- [ ] Reconsider the information density on CF and GH readme
- [ ] Client-side localization support

**Comment by Madis0** [comment]
https://github.com/Fabulously-Optimized/fabulously-optimized.github.io/issues/1
