### ISSUE TITLE
Title mod

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#252]
Todo for https://github.com/Fabulously-Optimized/fabric-title-changer:

- [ ] Refactor to a main menu text piece with this kind of mixin: https://github.com/PuzzleMC/Puzzle/blob/1.18/puzzle-base/src/main/java/net/puzzlemc/core/mixin/MixinTitleScreen.java
- [ ] Rebrand
- [ ] Update dependencies 
- [ ] Update meta (force latest loader, minimum java 17, no mc dep)
- [ ] Publish to CF
- [ ] Test on FO
- [ ] Remove 'Slight' GUI Modifications #18

**Comment by Madis0** [comment]
#304 will supersede this.
