### ISSUE TITLE
Improve description

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#513]
- [x] Make English ~~a normal paragraph in Modrinth~~ remove mention altogether
- [x] Make video thumbnail smaller, ~~add a title-author caption~~
    - Somehow it still has to be obvious that it is a video link
- [x] Simplify "Fabric does not include huge libraries" to "is lightweight" or similar
