### ISSUE TITLE
CLI tools for automation

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#91]
- [x] Mods/config from Curseforge to MultiMC
- [x] Curseforge/MultiMC/MultiMC2 files to Git
- [x] Packwiz update sequence
- [x] Fix Packwiz import
- [x] Support versioned Packwiz
- [x] Remove BAT
- [x] Packwiz to Modrinth
- [x] Fix PW to MR - copy index.json to git directly
- [x] Fix CF to Git - it doesn't copy the latest manifest and modlist
- [ ] ~~All in one script?~~
